# Generated by Django 2.2.2 on 2019-07-13 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, unique=True, verbose_name='имя')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='описание номера')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'номер',
                'verbose_name_plural': 'номера',
            },
        ),
        migrations.CreateModel(
            name='DateItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_item', models.DateField(verbose_name='дата бронирования')),
                ('status', models.CharField(choices=[['f', 'свободен'], ['b', 'занят'], ['e', 'empty']], default='e', max_length=1)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date', to='timetable.Room')),
            ],
            options={
                'verbose_name': 'дата бронирования',
                'verbose_name_plural': 'даты бронирования',
            },
        ),
    ]
