# Generated by Django 2.2.2 on 2019-07-01 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfText', models.CharField(max_length=70)),
                ('valueOfText', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfHotel', models.CharField(max_length=100, verbose_name='Название отеля')),
                ('tax', models.PositiveIntegerField(verbose_name='Налог')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, unique=True, verbose_name='имя')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('adults', models.PositiveIntegerField(verbose_name='Кол-во взрослых')),
                ('kids', models.PositiveIntegerField(verbose_name='Кол-во детей')),
                ('infants', models.PositiveIntegerField(verbose_name='Кол-во младенцев')),
                ('extraPerson', models.PositiveIntegerField(verbose_name='Цена за доп. человека')),
                ('image1', models.ImageField(blank=True, upload_to='rooms_img/%Y/%m/%d')),
                ('image2', models.ImageField(blank=True, upload_to='rooms_img/%Y/%m/%d')),
                ('description', models.TextField(blank=True, verbose_name='описание номера')),
            ],
            options={
                'verbose_name': 'номер',
                'verbose_name_plural': 'номера',
            },
        ),
        migrations.CreateModel(
            name='TableTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DateItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_item', models.DateField(verbose_name='дата бронирования')),
                ('is_busy', models.BooleanField(default=False, verbose_name='занят')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Room')),
            ],
            options={
                'verbose_name': 'дата бронирования',
                'verbose_name_plural': 'даты бронирования',
            },
        ),
    ]
